modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]] #optional
   modId="neoforge" #mandatory
   type="required"
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="geckolib3"
    type="required"
    versionRange="[3.0.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="mekanism"
    type="required"
    versionRange="[10.0.21,)"
    ordering="NONE"
    side="BOTH"
