modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
   modId="neoforge" #mandatory
   type="required"
   versionRange="[20.6,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.5.4,)"
    ordering="NONE"
    side="BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

